version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-west-1:904672846176:task-definition/service:14"
        LoadBalancerInfo:
          ContainerName: "hooli"
          ContainerPort: 8080
